name: GitHub Actions Demo
on: 
  # pull_request:
  push:
  
  workflow_dispatch:
env: 
  IMAGE_NAME: "hoge"
  IMAGE_TAG: "piyo"

jobs:
  push-image: 
    name: push-image
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    steps:
      - name: temporary
        run: |
          apk add git 
          git config --global http.sslverify false
          apk add docker
          find "hogehoge"
          echo ${{github.repository}}
