name: GitHub Actions Demo
on: 
  push:
   
  job3:
    name: job3
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    steps:
      - name: temporary
        run: |
          echo "fuga"
