name: GitHub Actions Demo
on: 
  push:
  
  workflow_dispatch:
  

jobs:
  check-pynacl: 
    name: check-pynacl
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    steps:
      - name: temp
        run: |
          apt install sudo
          pip list > list.txt
          echo "instal pynacl"
          cat <<EOF> requirement.txt
          ---
          PyNaCl~=1.3.0
          EOF
          sudo pip install -r requirement.txt
          sudo pip list.txt >> list.txt
          uniq list.txt
          cat list.txt
          
  check-jinja: 
    name: check-jinja
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    steps:
      - name: temp
        run: |
          apt install sudo
          pip list > list.txt
          echo "instal pynacl"
          cat <<EOF> requirement.txt
          ---
          Jinja2~=1.3.0
          EOF
          sudo pip install -r requirement.txt
          sudo pip list.txt >> list.txt
          uniq list.txt
          cat list.txt          
