name: GitHub Actions Demo
on: 
  push:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.5-239
    steps:
      - name: check-ubi-package
        run: |
          yum list installed > list.txt
          echo "cat list.txt"
          cat list.txt
          echo "yum info acl"
          yum info acl.x86_64
          yum list installed |  awk '7<=NR && NR<=190 {print $1}' > hoge.txt
          cat hoge.txt
          cat <<EOF > while.sh
            #!/bin/bash
            while read line
            do
              yum info $line
            done < ./hoge.txt
          EOF
          sh while.sh
