name: GitHub Actions Demo
on: 
  push:
   
  job3:
    name: job3
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.5-239
    steps:
      - name: check-ubi-package
        run: |
          yum list installed
