name: GitHub Actions Demo
on: 
  push:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.5-239
    steps:
      - name: check-ubi-package
        run: |
          yum info acl.x86_64
          yum info audit-libs.x86_64
          yum info basesystem.noarch
          yum info bash.x86_64
          yum info brotli.x86_64
          yum info bzip2-libs.x86_64
          yum info ca-certificates.noarch
          yum info chkconfig.x86_64
          yum info coreutils-single.x86_64
          yum info cracklib.x86_64
          yum info cracklib-dicts.x86_64
          yum info crypto-policies.noarch
          yum info crypto-policies-scripts.noarch
          yum info cryptsetup-libs.x86_64
          yum info curl.x86_64
          yum info cyrus-sasl-lib.x86_64
          yum info dbus.x86_64
          yum info dbus-common.noarch
          yum info dbus-daemon.x86_64
          yum info dbus-glib.x86_64
          yum info dbus-libs.x86_64
          yum info dbus-tools.x86_64
          yum info device-mapper.x86_64
          yum info device-mapper-libs.x86_64
          yum info dmidecode.x86_64
          yum info dnf.noarch
          yum info dnf-data.noarch
          yum info dnf-plugin-subscription-manager.x86_64
          yum info elfutils-default-yama-scope.noarch
          yum info elfutils-libelf.x86_64
          yum info elfutils-libs.x86_64
          yum info expat.x86_64
          yum info file-libs.x86_64
          yum info filesystem.x86_64
          yum info findutils.x86_64
          
