name: GitHub Actions Demo
on: 
  push:
  
  workflow_dispatch:
env: 
  IMAGE_NAME: "hoge"
  IMAGE_TAG: "piyo"

jobs:
  test1:
    name: test1
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    steps:
      - name: temporary
        run: |
          echo "hogehoge"
          
  test2:
    name: test2
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    if: startsWith(github.ref, 'regs/heads/hogehoge-')
    steps:
      - name: temporary
        run: |
          echo "piyo"


  test3:
    name: test3
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    if: startsWith(github.ref, 'regs/heads/hogehoge-')
    steps:
      - name: temporary
        run: |
          echo "piyo"
