name: GitHub Actions Demo
on: 
  push:

jobs:
  job1: 
    name: job1
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    steps:
      - name: temporary
        run: |
          apk -h
          echo "hogehoge"
          apk list --installed
          echo "fugafuga"
          apk -L info
