name: GitHub Actions Demo
on: 
  push:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.5-239
    steps:  
       - name: check-ubi-package
         run: |
          yum install unzip -y
          yum install zip -y
          curl -s https://get.sdkman.io | bash
          sdk install gradle
#           cat <<EOF > build.gradle
#             task wrapper(type: Wrapper) {
#             gradleVersion = '1.11'
#             }
#           EOF
