name: GitHub Actions Demo
on: 
  push:
  
env: 
  IMAGE_NAME: "hogeee"
  IMAGE_TAG: "piyo"

jobs:
# use bash, use bash regular expression
# success
  push-image: 
    name: push-image
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    steps:
      - name: temporary
        run: |
          apk add bash
      - name: temporary2
        shell: bash
        run: |
          if [[ ${{env.IMAGE_NAME}} =~ hoge*$ ]]; then
            echo "hoge"
          else
            echo "hogehoge"
          fi
          
          
  push-image2: 
  # use ash/sh, use case, use regular expression
  # failure
    name: push-image2
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    steps:
      - name: temporary2
        run: 
          case "${{env.IMAGE_NAME}}" in 
              ^hoge.*$)
                echo "hoge" 
                ;;
              *)
                echo "hogehoge"
                ;;
          esac

  push-image3: 
    # use ash/sh, use regular expression, use ${}
    # failure
    name: push-image3
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    steps:
      - name: temporary3
        run: 
          if [ "${{env.IMAGE_NAME}}" = ${^hoge.*$} ]; then
              echo "hoge"
          else
              echo "hogehoge"
          fi

