name: GitHub Actions Demo
on: 
  push:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.5-239
    steps:
      - name: check-ubi-package
        run: |
          yum info acl.x86_64
          yum info audit-libs.x86_64
          yum info basesystem.noarch
          yum info bash.x86_64
          yum info brotli.x86_64
          yum info bzip2-libs.x86_64
          yum info ca-certificates.noarch
          yum info chkconfig.x86_64
          yum info coreutils-single.x86_64
          yum info cracklib.x86_64
          yum info cracklib-dicts.x86_64
          yum info crypto-policies.noarch
          yum info crypto-policies-scripts.noarch
          yum info cryptsetup-libs.x86_64
          yum info curl.x86_64
          yum info cyrus-sasl-lib.x86_64
          yum info dbus.x86_64
          yum info dbus-common.noarch
          yum info dbus-daemon.x86_64
          yum info dbus-glib.x86_64
          yum info dbus-libs.x86_64
          yum info dbus-tools.x86_64
          yum info device-mapper.x86_64
          yum info device-mapper-libs.x86_64
          yum info dmidecode.x86_64
          yum info dnf.noarch
          yum info dnf-data.noarch
          yum info dnf-plugin-subscription-manager.x86_64
          yum info elfutils-default-yama-scope.noarch
          yum info elfutils-libelf.x86_64
          yum info elfutils-libs.x86_64
          yum info expat.x86_64
          yum info file-libs.x86_64
          yum info filesystem.x86_64
          yum info findutils.x86_64
          yum info gawk.x86_64
          yum info gdb-gdbserver.x86_64
          yum info gdbm.x86_64
          yum info gdbm-libs.x86_64
          yum info glib2.x86_64
          yum info glibc.x86_64
          yum info glibc-common.x86_64
          yum info glibc-minimal-langpack.x86_64
          yum info gmp.x86_64
          yum info gnupg2.x86_64
          yum info gnutls.x86_64
          yum info gobject-introspection.x86_64
          yum info gpgme.x86_64
          yum info grep.x86_64
          yum info gzip.x86_64
          yum info ima-evm-utils.x86_64
          yum info info.x86_64
          yum info json-c.x86_64
          yum info json-glib.x86_64
          yum info keyutils-libs.x86_64
          yum info kmod-libs.x86_64
          yum info krb5-libs.x86_64
          yum info langpacks-en.noarch
          yum info libacl.x86_64
          yum info libarchive.x86_64
          yum info libassuan.x86_64
          yum info libattr.x86_64
          yum info libblkid.x86_64
          yum info libcap.x86_64
          yum info libcap-ng.x86_64
          yum info libcom_err.x86_64
          yum info libcomps.x86_64
          yum info libcurl.x86_64
          yum info libdb.x86_64
          yum info libdb-utils.x86_64
          yum info libdnf.x86_64
          yum info libfdisk.x86_64
          yum info libffi.x86_64
          yum info libgcc.x86_64
          yum info libgcrypt.x86_64
          yum info libgpg-error.x86_64
          yum info libksba.x86_64
          yum info libmodulemd.x86_64
          yum info libmount.x86_64
          yum info libnghttp2.x86_64
          yum info libnl3.x86_64
          yum info libnsl2.x86_64
          yum info libpsl.x86_64
          yum info libpwquality.x86_64
          yum info librepo.x86_64
          yum info libreport-filesystem.x86_64
          yum info librhsm.x86_64
          yum info libseccomp.x86_64
          yum info libselinux.x86_64
          yum info libsemanage.x86_64
          yum info libsepol.x86_64
          yum info libsigsegv.x86_64
          yum info libsmartcols.x86_64
          yum info libsolv.x86_64
          yum info libssh.x86_64
          yum info libssh-config.noarch
          yum info libstdc++.x86_64
          yum info libtasn1.x86_64
          yum info libtirpc.x86_64
          yum info libunistring.x86_64
          yum info libusbx.x86_64
          yum info libuser.x86_64
          yum info libutempter.x86_64
          yum info libuuid.x86_64
          yum info libverto.x86_64
          yum info libxcrypt.x86_64
          yum info libxml2.x86_64
          yum info libyaml.x86_64
          yum info libzstd.x86_64
          yum info lua-libs.x86_64
          yum info lz4-libs.x86_64
          yum info mpfr.x86_64
          yum info ncurses-base.noarch
          yum info ncurses-libs.x86_64
          yum info nettle.x86_64
          yum info npth.x86_64
          yum info openldap.x86_64
          yum info openssl-libs.x86_64
          yum info p11-kit.x86_64
          yum info p11-kit-trust.x86_64
          yum info pam.x86_64
          yum info passwd.x86_64
          yum info pcre.x86_64
          yum info pcre2.x86_64
          yum info platform-python.x86_64
          yum info platform-python-setuptools.noarch
          yum info popt.x86_64
          yum info publicsuffix-list-dafsa.noarch
          yum info python3-chardet.noarch
          yum info python3-cloud-what.x86_64
          yum info python3-dateutil.noarch
          yum info python3-dbus.x86_64
          yum info python3-decorator.noarch
          yum info python3-dmidecode.x86_64
          yum info python3-dmidecode.x86_64
          yum info python3-dnf-plugins-core.noarch
          yum info python3-ethtool.x86_64
          yum info python3-gobject-base.x86_64
          yum info python3-gpg.x86_64
          yum info python3-hawkey.x86_64
          yum info python3-idna.noarch
          yum info python3-iniparse.noarch
          yum info python3-inotify.noarch
          yum info python3-libcomps.x86_64
          yum info python3-libdnf.x86_64
          yum info python3-librepo.x86_64
          yum info python3-libs.x86_64
          yum info python3-libxml2.x86_64
          yum info python3-pip-wheel.noarch
          yum info python3-pysocks.noarch
          yum info python3-requests.noarch
          yum info python3-rpm.x86_64
          yum info python3-setuptools-wheel.noarch
          yum info python3-six.noarch
          yum info python3-subscription-manager-rhsm.x86_64
          yum info python3-syspurpose.x86_64
          yum info python3-urllib3.noarch
          yum info readline.x86_64
          yum info redhat-release.x86_64
          yum info rootfiles.noarch
          yum info rpm.x86_64
          yum info rpm-build-libs.x86_64
          yum info rpm-libs.x86_64
          yum info sed.x86_64
          yum info setup.noarch
          yum info shadow-utils.x86_64
          yum info sqlite-libs.x86_64
          yum info subscription-manager.x86_64
          yum info subscription-manager-rhsm-certificates.x86_64
          yum info systemd.x86_64
          yum info systemd-libs.x86_64
          yum info systemd-pam.x86_64
          yum info tar.x86_64
          yum info tpm2-tss.x86_64
          yum info tzdata.noarch
          yum info util-linux.x86_64
          yum info vim-minimal.x86_64
          yum info virt-what.x86_64
          yum info which.x86_64
          yum info xz-libs.x86_64
          yum info yum.noarch
          yum info zlib.x86_64
          
          
