name: GitHub Actions Demo
on: 
  # pull_request:
  push:
  
  workflow_dispatch:
env: 
  IMAGE_NAME: "hogepiyo"
  IMAGE_TAG: "piyo"

jobs:
  push-image: 
    name: push-image
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
    container:
      image: alpine:3.14.2
    steps:
      - name: temporary
        run: |
          apk add bash
      - name: temporary2
        shell: bash
        run: |
          # if [ "${{env.IMAGE_NAME}}" == "hoge" ]
          if [ "${{env.IMAGE_NAME}}" =~ ^hoge.*$ ]
          then
              echo "hoge"
          else
              echo "hogehoge"
          fi

  push-image2: 
    name: push-image
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    steps:
      - name: temporary2
      - run: |
        if [ expr "${{env.IMAGE_NAME}}" : "^hoge.*$" >/dev/null ] 
        then
            echo "hoge" 
        else 
            echo "hogehoge"
        fi
if expr "$input" : "[0-9]*$" >&/dev/null;then
  echo "$input is a number"
else
  echo "$input is not a number"
fi
