name: GitHub Actions Demo
on: 
  # pull_request:
  push:


jobs:
  push-image: 
    name: push-image
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    steps:
      - name: temporary
        run: |
          echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}'
          echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}'
   
