name: GitHub Actions Demo
on: 
  push:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.5-239
    steps:
      - name: check-ubi-package
        run: |
          yum list installed
          yum list installed |  awk '7<=NR && NR<=190 {print $1}' > hoge.txt
          cat hoge.txt
          cat <<EOF > while.sh
            #!/bin/bash
            while read line
            do
              yum info $line | sed -n "/Available Packages/q;p" > name.txt
              grep Name name.txt >> info.txt
              grep URL name.txt >> info.txt
              grep License name.txt >> info.txt
              echo " " >> info.txt
            done < ./hoge.txt
          EOF
          cat info.txt
#          yum info audit-libs.x86_64 | sed -n "/Available Packages/q;p" > name.txt
#          grep Name name.txt >> info.txt
#          grep URL name.txt >> info.txt
#          grep License name.txt >> info.txt
#          echo " " >> info.txt
#          grep License name.txt >> info.txt
#          cat info.txt
          
          
           
          
 #         cat <<EOF > while.sh
 #           #!/bin/bash
 #           while read line
 #           do
 #             yum info $line | grep Name >> name.txt
 #           done < ./hoge.txt
 #         EOF
 #         sh while.sh 
 #         cat name.txt
 #     - name: install artifact
 #       uses: actions/upload-artifact@v2
 #       with:
 #         name: hoge
 #         path: name.txt        
 
 
 
#        - name: install artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: hoge
#           path: hoge.txt   
