name: GitHub Actions Demo
on: 
  push:

jobs:
# check os package dependencies
  job1: 
    name: job1
    runs-on: ubuntu-latest
    container:
      image: alpine:3.15.0
    steps:
      - name: temporary
        run: |
          echo "hogehoge"
          apk list --installed
          echo "fugafuga"
          apk -L info
          echo "piyopiyo"
          apk info -vv | sort
          
# check language package dependencies
  job2: 
    name: job2
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    steps:
      - name: temporary
        run: |
          apt-get update
          apt-get install -y sudo
          sudo pip show
          sudo pip install numpy
          
