name: GitHub Actions Demo
on: 
  push:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.5-239
    steps:  
       - name: check-ubi-package
         run: |
          cat <<EOF > build.gradle
            task wrapper(type: Wrapper) {
            gradleVersion = '1.11'
            }
          EOF
          gradle wrapper
        
