name: GitHub Actions Demo
on: 
  pull_request:
    branches:
      - develop
    
  push:
    branches:
      - "feature-**"
      
  
  workflow_dispatch:
env: 
  IMAGE_NAME: "hoge"
  IMAGE_TAG: "piyo"

jobs:
  hoge1: 
    name: hoge1
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.2
    steps:
      - name: temporary
        run: |
          echo "hogehoge"
