name: GitHub Actions Demo
on: 
  push:

jobs:
# check os package dependencies
  job1: 
    name: job1
    runs-on: ubuntu-latest
    container:
      image: alpine:3.15.0
    steps:
      - name: temporary
        run: |
          echo "hogehoge"
          apk list --installed
          echo "fugafuga"
          apk -L info
          echo "piyopiyohoge"
          apk info -vv | sort
          
# check language package dependencies
  job2: 
    name: job2
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    steps:
      - name: temporary
        run: |
          apt-get update
          apt-get install -y sudo
          sudo pip install numpy
          pip list
          echo "hoge"
          pip freeze

  job3: 
    name: job3
    runs-on: ubuntu-latest
    container:
      image: alpine:3.15.0
    steps:
      - name: temporary
        run: |
          echo "list installed packages"
          apk list --installed
          echo "list installed packages"
          apk -L info
          echo "install jdk"
          apk add openjdk11
          echo "list installed packages"
          apk -L info | sort          
          
  job4:
    name: job4
    runs-on: ubuntu-latest
    container:
      image: openjdk:11-jre-slim-buster
    steps:
      - name: temporary
        run: |
          echo "list installed packages"
          apt list --installed

  job5:
    name: job5
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk11:x86_64-alpine-jre11u-2022-02-11-03-47-beta-nightly
    steps:
      - name: temporary
        run: |
          echo "list installed packages"
          apt list --installed

