name: CI Package 3
on: 
#  push:
  workflow_dispatch:


jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.5-239
    steps:
      - name: check-ubi-package
        run: |
          dnf install -y git-2.31.1-2.el8
          dnf deplist git-2.31.1-2.el8
          yum list installed
          yum list installed | awk '7<=NR && NR<=203 {print $1}' > hoge.txt
          cat hoge.txt
          cat <<EOF > while.sh
            #!/bin/bash
            while read line
            do
              echo $line
              yum info $line | sed -n "/Available Packages/q;p" > name.txt
              grep Name name.txt >> info.txt
              grep Version name.txt >> info.txt
              grep Release name.txt >> info.txt
              grep URL name.txt >> info.txt
              grep License name.txt >> info.txt
              echo " " >> info.txt
            done <./hoge.txt
          EOF
          sh while.sh 
      - name: install artifact
        uses: actions/upload-artifact@v2
        with:
          name: hoge
          path: hoge.txt, info.txt
#       - name: info
#         run: | 
#           dnf info jq.x86_64
#           dnf info oniguruma.x86_64
#           echo hoge
          
          
