name: CI Package
on: 
#  push:
  workflow_dispatch:


jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.5-239
    steps:
      - name: check-ubi-package
        run: |
          dnf install -y buildah-1:1.24.2-4.module+el8.6.0+14877+f643d2d6.x86_64
          dnf deplist buildah-1:1.24.2-4.module+el8.6.0+14877+f643d2d6.x86_64
          yum list installed |  awk '7<=NR && NR<=203 {print $1}' > hoge.txt
          cat hoge.txt
      - name: install artifact
        uses: actions/upload-artifact@v2
        with:
          name: hoge
          path: hoge.txt 
