name: CI Package
on: 
#  push:
  workflow_dispatch:


jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.5-239
    steps:
      - name: check-ubi-package
        run: |
          dnf install -y buildah-1:1.24.2-4.module+el8.6.0+14877+f643d2d6.x86_64
          dnf deplist buildah-1:1.24.2-4.module+el8.6.0+14877+f643d2d6.x86_64
          yum list installed |  awk '7<=NR && NR<=203 {print $1}' > hoge.txt
          cat hoge.txt
      - name: install artifact
        uses: actions/upload-artifact@v2
        with:
          name: hoge
          path: hoge.txt 
      - name: info
        run: |
          dnf info buildah.x86_64
          dnf info containers-common.x86_64
          dnf info criu.x86_64
          dnf info fuse-common.x86_64
          dnf info fuse-overlayfs.x86_64
          dnf info fuse3.x86_64
          dnf info fuse3-libs.x86_64
          dnf info iptables-libs.x86_64
          dnf info jansson.x86_64
          dnf info kmod.x86_64
          dnf info libibverbs.x86_64
          dnf info libmnl.x86_64
          dnf info libnet.x86_64
          dnf info libnftnl.x86_64
          dnf info libpcap.x86_64
          dnf info libslirp.x86_64
          dnf info nftables.x86_64
          dnf info protobuf-c.x86_64
          dnf info runc.x86_64
          dnf info slirp4netns.x86_64
