name: Gradle
on: 
  push:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    container:
      image: openjdk:11-jdk
    steps:  
       - name: check-ubi-package
         run: |
          apt update 
          apt install gradle -y
          gradle wrapper
          

