name: Setup Tool
on: 
#  push:
  workflow_dispatch:


jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.5-239
    steps:
      - name: check-ubi-package
        run: |
          yum install python38 -y
          yum list installed
          python3 -V 
          pip3 help
          # pip help
          # cat <<EOF > requirement.txt
          # Jinja2==3.1.2
          # MarkupSafe==2.1.1
          # PyNaCl==1.5.0
          # cffi==1.15.0
          # pycparser==2.21
          # EOF
          # pip install -r requirement.txt 
          
          # pip list installed
          
      
